# Generated by Django 4.2.1 on 2023-06-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_menu_restaurant_category_ids_seating_queue_menuitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='seating',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
        migrations.DeleteModel(
            name='Seating',
        ),
    ]
