# Generated by Django 4.2.1 on 2023-06-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.5, max_digits=7),
        ),
    ]
