# Generated by Django 4.2.1 on 2023-06-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_item_price_remove_item_quantity_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category_ids',
        ),
        migrations.AddField(
            model_name='category',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
