# Generated by Django 4.2.1 on 2023-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_remove_restaurant_category_ids_category_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='square_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='square_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='square_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
