# Generated by Django 4.2.1 on 2023-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_user_restaurant_available_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='available_seats',
            field=models.IntegerField(default=20),
        ),
    ]
