# Generated by Django 4.2.1 on 2023-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_restaurant_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seated',
            field=models.BooleanField(default=False),
        ),
    ]
