# Generated by Django 4.2.1 on 2023-06-06 00:26

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_user_is_seated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_order_identifier', models.CharField(default=restaurants.models.generate_uoi, max_length=6, unique=True)),
                ('order_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
